import type { StoreApp, StoreReview } from "./types";

export const DEMO_APPS: StoreApp[] = [
  { storeAppId: "demo.focusflow", name: "FocusFlow (sample)", bundleId: "com.example.focusflow" },
  { storeAppId: "demo.pocketbudget", name: "PocketBudget (sample)", bundleId: "com.example.pocketbudget" },
];

export const DEMO_LIVE_VERSIONS: Record<string, string> = {
  "demo.focusflow": "2.3.0",
  "demo.pocketbudget": "1.8.2",
};

type Seed = Omit<StoreReview, "reviewedAt" | "reply"> & { hoursAgo: number; reply?: string };

const SEEDS: Record<string, Seed[]> = {
  "demo.focusflow": [
    {
      storeReviewId: "ff-1",
      rating: 1,
      title: "Timer stops when I lock my phone",
      body: "Every time I lock the screen the focus timer pauses. Lost three sessions today. Was great before the last update.",
      author: "maya_writes",
      territory: "USA",
      language: "en",
      appVersion: "2.3.0",
      device: null,
      hoursAgo: 3,
    },
    {
      storeReviewId: "ff-2",
      rating: 2,
      title: "Widgets are blank",
      body: "The home screen widget just shows an empty box since iOS 27. Please fix, it's the main reason I bought Pro.",
      author: "Deepak R",
      territory: "IND",
      language: "en",
      appVersion: "2.3.0",
      device: null,
      hoursAgo: 9,
    },
    {
      storeReviewId: "ff-3",
      rating: 5,
      title: "Finally a focus app that isn't cluttered",
      body: "Clean, fast, and the weekly report is genuinely useful. Would love an Apple Watch app someday.",
      author: "tomhdev",
      territory: "GBR",
      language: "en",
      appVersion: "2.3.0",
      device: null,
      hoursAgo: 20,
    },
    {
      storeReviewId: "ff-4",
      rating: 1,
      title: "Se cierra al abrir estadísticas",
      body: "La app se cierra cada vez que abro la pestaña de estadísticas. Tengo un iPhone 13.",
      author: "lucia.m",
      territory: "ESP",
      language: "es",
      appVersion: "2.3.0",
      device: null,
      hoursAgo: 30,
    },
    {
      storeReviewId: "ff-5",
      rating: 3,
      title: "Good but pricey",
      body: "Works well but $6.99 a month for a timer feels steep. A lifetime option would get my money.",
      author: "budget_ben",
      territory: "CAN",
      language: "en",
      appVersion: "2.2.4",
      device: null,
      hoursAgo: 52,
    },
    {
      storeReviewId: "ff-6",
      rating: 4,
      title: "Almost perfect",
      body: "Please add a way to export sessions to CSV. Otherwise love it.",
      author: "k.nakamura",
      territory: "JPN",
      language: "en",
      appVersion: "2.2.4",
      device: null,
      hoursAgo: 80,
      reply: "Thanks! CSV export is on our list for the next few releases.",
    },
    // Two more reports of ff-1's bug, so the sample shows reviews being grouped into one issue.
    {
      storeReviewId: "ff-7",
      rating: 2,
      title: "Timer pauses on the lock screen",
      body: "The timer keeps stopping whenever my phone locks. I use it for studying, please fix.",
      author: "noor.k",
      territory: "ARE",
      language: "en",
      appVersion: "2.3.0",
      device: null,
      hoursAgo: 16,
    },
    {
      storeReviewId: "ff-8",
      rating: 1,
      title: "Sessions stop when the screen locks",
      body: "Focus sessions stop as soon as the screen locks. Useless for long sessions now.",
      author: "felixb",
      territory: "DEU",
      language: "en",
      appVersion: "2.3.0",
      device: null,
      hoursAgo: 26,
    },
  ],
  "demo.pocketbudget": [
    {
      storeReviewId: "pb-1",
      rating: 1,
      title: null,
      body: "Bank sync fails with 'error 502' every morning. I have to reconnect my account daily.",
      author: "Arjun Mehta",
      territory: null,
      language: "en-IN",
      appVersion: "1.8.2",
      device: "Pixel 9",
      hoursAgo: 5,
    },
    {
      storeReviewId: "pb-2",
      rating: 2,
      title: null,
      body: "Die App stürzt ab, wenn ich eine Kategorie lösche.",
      author: "Jonas W.",
      territory: null,
      language: "de-DE",
      appVersion: "1.8.2",
      device: "Galaxy S25",
      hoursAgo: 14,
    },
    {
      storeReviewId: "pb-3",
      rating: 5,
      title: null,
      body: "Best budgeting app I've tried. The monthly summary notification keeps me honest.",
      author: "Priya S",
      territory: null,
      language: "en-IN",
      appVersion: "1.8.2",
      device: "OnePlus 13",
      hoursAgo: 40,
    },
    {
      storeReviewId: "pb-4",
      rating: 3,
      title: null,
      body: "How do I share a budget with my partner? Couldn't find it anywhere.",
      author: "Chris P",
      territory: null,
      language: "en-US",
      appVersion: "1.8.1",
      device: "Pixel 8a",
      hoursAgo: 70,
    },
    {
      storeReviewId: "pb-5",
      rating: 2,
      title: null,
      body: "Bank sync keeps failing and I have to reconnect my bank every single day.",
      author: "Meera N",
      territory: null,
      language: "en-IN",
      appVersion: "1.8.2",
      device: "Galaxy A55",
      hoursAgo: 22,
    },
  ],
};

export function demoReviews(storeAppId: string, now = Date.now()): StoreReview[] {
  return (SEEDS[storeAppId] ?? []).map(({ hoursAgo, reply, ...seed }) => {
    const reviewedAt = new Date(now - hoursAgo * 3600 * 1000).toISOString();
    return {
      ...seed,
      reviewedAt,
      reply: reply ? { text: reply, id: null, repliedAt: reviewedAt } : null,
    };
  });
}
