// Builds src/views/icons.generated.ts from Phosphor's official SVG files (@phosphor-icons/core, MIT),
// so pages inline only the icons they use. Add a name below and run: npm run icons
import { readFileSync, writeFileSync } from "node:fs";

const ICONS = {
  star: "fill/star-fill",
  github: "fill/github-logo-fill",
  "arrow-right": "regular/arrow-right",
  "arrow-up-right": "regular/arrow-up-right",
  check: "regular/check",
  "check-circle": "regular/check-circle",
  "caret-down": "regular/caret-down",
  stack: "regular/stack",
  rocket: "regular/rocket-launch",
  sparkle: "regular/sparkle",
  globe: "regular/globe-simple",
  "chart-bar": "regular/chart-bar",
  siren: "regular/siren",
  "bell-ringing": "regular/bell-ringing",
  "lock-key": "regular/lock-key",
  key: "regular/key",
  "list-magnifying-glass": "regular/list-magnifying-glass",
  "shield-check": "regular/shield-check",
  devices: "regular/devices",
};

const lines = Object.entries(ICONS).map(([name, file]) => {
  const svg = readFileSync(new URL(`../node_modules/@phosphor-icons/core/assets/${file}.svg`, import.meta.url), "utf8");
  const match = svg.match(/^<svg[^>]*viewBox="0 0 256 256"[^>]*>([\s\S]*)<\/svg>\s*$/);
  if (!match) throw new Error(`Unexpected SVG format in ${file}.svg`);
  return `  ${JSON.stringify(name)}: ${JSON.stringify(match[1])},`;
});

writeFileSync(
  new URL("../src/views/icons.generated.ts", import.meta.url),
  [
    "// Generated by scripts/icons.mjs from Phosphor Icons (MIT, phosphoricons.com). Don't edit by hand.",
    "export const ICON_PATHS = {",
    ...lines,
    "} as const;",
    "",
    "export type IconName = keyof typeof ICON_PATHS;",
    "",
  ].join("\n"),
);
console.log(`Wrote ${lines.length} icons.`);
